
# Análisis de ASVs con QIIME2 {.unnumbered}

El análisis microbiano basado en secuenciación de amplicones ha sido ampliamente utilizado para la caracterización de comunidades microbianas en una amplia variedad de ambientes y sistemas biológicos. Este enfoque se fundamenta en la amplificación y secuenciación de genes marcadores específicos, lo que permite inferir la composición taxonómica de las comunidades microbianas. En este contexto, el Amplicon Sequence Variant (ASV) se define como una entidad biológica única, ofreciendo una resolución taxonómica superior en comparación con la tradicional Operational Taxonomic Unit (OTU).

En el análisis de secuenciación de amplicones, la derreplicación es un paso clave que consiste en colapsar lecturas idénticas en secuencias únicas con su abundancia asociada, reduciendo la redundancia generada por PCR y secuenciación y preservando la variación exacta de las secuencias; a diferencia del clustering en OTUs con umbrales arbitrarios, este proceso no implica pérdida de información y no corrige errores por sí mismo, sino que constituye un paso previo indispensable para la inferencia de Amplicon Sequence Variants (ASVs) mediante modelos estadísticos de error, como los implementados en DADA2, que permiten distinguir entre errores técnicos y variantes biológicas reales.

Desde una perspectiva ecológica, la integración de la derreplicación con modelos explícitos de corrección de error contribuye a reducir sesgos computacionales y de conteo que pueden inflar artificialmente las estimaciones de riqueza y abundancia relativa. Como resultado, se obtiene una representación más fiel de la estructura y composición de las comunidades microbianas, lo que fortalece la interpretación ecológica de los patrones observados. En este trabajo, se emplean las herramientas implementadas en QIIME 2 para ilustrar cómo la derreplicación, junto con otros procesos de control de calidad y modelación estadística, sustenta la inferencia robusta de ASVs a partir de datos de secuenciación de amplicones.

:::{.callout-note appearance="simple"}
## Objetivos

Comprender y aplicar el flujo de análisis de datos de secuenciación de amplicones en QIIME 2, desde la importación de datos hasta la obtención e interpretación de Amplicon Sequence Variants (ASVs) y la construcción de árboles filogenéticos:

1. Importar datos de secuenciación de amplicones en QIIME 2 y generar los artefactos necesarios para su análisis.
2. Integrar de manera adecuada los archivos manifest y metadata para garantizar una correcta asociación entre secuencias y muestras.
3. Inferir Amplicon Sequence Variants (ASVs) mediante el uso de DADA2, incorporando los pasos de derreplicación y corrección de errores.
4. Explorar e interpretar los archivos de salida para analizar las frecuencias y la distribución de los ASVs obtenidos.
:::

## I. Preparación del ambiente de trabajo

1. Ingrese a la cuenta del clúster.

2. En su directorio, cree un nuevo directorio y nómbrelo `Taller3_Qiime2`.

3. Copie todo el directorio `taller_3` a su directorio `Taller3_Qiime2`. La siguiente es la ruta donde encuentran el archivo a copiar: `/hpcfs/home/cursos/bcom4102/datasets/taller3/`

4. En los cuatro archivos proporcionados encontrará un script ejecutable con extensión `.sh`. Ejecútelo utilizando como argumento el archivo `accesionsSoil.txt` mediante el siguiente comando: `sbatch downloadReadsJob.sh accesionsSoil.txt`. Una vez finalizada la descarga, determine si las lecturas obtenidas corresponden a datos single-end o paired-end. Luego, realice una comparación entre este job y el utilizado en el Taller 2, analizando las diferencias en la estrategia de descarga de datos e identificando los cambios introducidos en el flujo de trabajo.

5. Inicie una sesión interactiva preferiblemente con 20G de memoria y al menos 4 cpus per task.

6. Cargue el módulo de QIIME2 disponible en el clúster.

:::{.callout-important appearance="simple"}
Qiime2 es un programa con mucho apoyo de los desarrolladores, muchas personas lo usan y cuando surgen errores estos se han reportado y solucionado en su [foro](https://forum.qiime2.org/). Si tienen problemas esta es su principal herramienta para solucionarlos, aun así, si el problema persiste pueden consultarlo con los monitores.
:::

# II. Importar datos a QIIME2

6. Para ejecutar `QIIME 2`, se requieren dos archivos fundamentales: un archivo *manifest* y un archivo de *metadata*. El archivo *manifest* establece la relación explícita entre cada muestra biológica y los archivos FASTQ que contienen sus lecturas de secuenciación, mientras que el archivo de *metadata* describe las variables asociadas a dichas muestras.

    El archivo `manifest.csv` debe contener, al menos, las columnas `sample-id`, `absolute-filepath` y `direction`. La columna `sample-id` corresponde al identificador lógico de la muestra y debe coincidir exactamente con los identificadores utilizados en el archivo de metadata. La columna `absolute-filepath` especifica la ruta absoluta al archivo FASTQ asociado a cada muestra, permitiendo a QIIME 2 localizar los datos de entrada. Finalmente, la columna `direction` indica la orientación de las lecturas (*forward o reverse*), lo cual es esencial para el correcto manejo de datos *single-end* o *paired-end* durante los pasos posteriores del análisis.

    Por ahora, solo complete el archivo `manifest.tsv` indicando la ubicación de las lecturas descargadas y asignando identificadores de muestra que permitan reconocer claramente la accesión de origen. Asegúrese de que el archivo esté separado por tabulaciones (`.tsv`) y que no contenga inconsistencias entre el manifest y el metadata. Una vez finalizado, verifique cuidadosamente el contenido del archivo y tome una captura de pantalla como evidencia del procedimiento.

7. A continuación, se procederá a importar los datos de secuenciación en QIIME 2 con el fin de convertirlos en un formato compatible con su flujo de análisis. En esta etapa se utilizará únicamente el archivo manifest para generar un artefacto en formato `.qza`. Antes de continuar, responda: ¿qué es un artefacto en QIIME 2 y cuál es su función dentro del flujo de trabajo? 

8. La creación del artefacto se realizará mediante el siguiente comando. Reemplace los valores `X`, `Y` y `Z` por los parámetros apropiados, apoyándose en la [documentación](https://amplicon-docs.qiime2.org/en/stable/) oficial de QIIME 2 o en la opción `--help` del comando:

```bash
qiime tools import \
  --type X \
  --input-path soilManifest.tsv \
  --output-path Y \
  --input-format Z
```

9. Una vez generado el artefacto que contiene los datos importados, se creará un archivo de visualización (.qzv) que permita explorar de forma resumida la información asociada a las lecturas de secuenciación. Para ello, utilice el siguiente comando, identificando correctamente cuál es el artefacto de entrada (Y) en este paso:

```bash
qiime demux summarize \
  --i-data Y \
  --o-visualization summSoil.qzv
```

10. Descargue el archivo de visualización generado y cárguelo en el [módulo web de visualización](https://view.qiime2.org/) de QIIME 2. A partir de la información presentada en el summary, identifique las muestras con el mayor y el menor número de secuencias, así como el número promedio de secuencias por muestra.

11. Examine la pestaña correspondiente a la calidad de las secuencias y describa de manera crítica los patrones observados. ¿Qué puede inferir sobre la calidad global de los datos y sus posibles implicaciones para los pasos posteriores del análisis? Adjunte las gráficas de calidad presentadas en la visualización como parte de su reporte.


# III. Generación de ASVs

12. En este paso se realiza simultáneamente la derreplicación, el denoising y la generación de las ASVs. Esto se puede realizar con DADA2 en su modo de single end. Haga un *job* utilizando el siguiente comando, solicitando al menos 20G de memoria, 4 cpus per task, y un tiempo de ejecución de 24 horas.

```bash
qiime dada2 denoise-single --i-demultiplexed-seqs A\ 
    --p-trim-left B\ 
    --p-trunc-len C\ 
    --o-table tableSoil.qza\ 
    --p-n-threads D \
    --o-representative-sequences repSeqSoil.qza\ 
    --o-denoising-stats denoisingStatsSoil.qza
```

:::{.callout-important appearance="simple"}
Usted deberá seleccionar los valores `A`,`B`, `C` y `D` con base en la información disponible en la visualización de los datos importados en la pestaña de *interactive quality plot*. `--p-n-threads` debe coincidir con el número de CPUs que solicite. ´Para saber que significan los flags puede apoyarse de la documentación y usar `--help`. Explique al final porqué eligió esos valores.
:::

13. A continuación, se convertirán la tabla de características y las estadísticas de denoising en archivos de visualización. Para ello, será necesario contar con un archivo de *metadata*, el cual deberá ser construido por usted. En este archivo se incluirán, para cada muestra, el identificador de muestra `sample-id` utilizado en el archivo *manifest*, el código de accesión SRA correspondiente y la clasificación del tipo de cultivo del cual proviene la muestra.

    El archivo de *metadata* deberá estar separado por tabulaciones (`.tsv`). Una vez completado, verifique cuidadosamente su contenido y tome una captura de pantalla como evidencia del procedimiento. Posteriormente, ejecute el siguiente comando, reemplazando X por el archivo de metadata correspondiente:

```bash
qiime feature-table summarize\
    --i-table X\
    --o-visualization summSoil2.qzv\
    --m-sample-metadata-file soilMetadata.tsv
```

    También corra este comando para obtener las estadísticas de DADA2:

```bash
qiime metadata tabulate\
    --m-input-file denoisingStatsSoil.qza\
    --o-visualization summSoil3.qzv
```

    Finalmente para este punto:

    - Visualice el archivo de estadísticas de DADA2 y describa qué filtro se hace en cada uno de los pasos del proceso.
    - Indique el número de features totales que obtuvo después del proceso y para que los podrá utilizar más adelante.
    - ¿Cuál es el máximo corte de lecturas que puede tomar para conservar todas las muestras?

    Adjunte imágenes de las tablas o gráficos que apoyen sus respuestas.


