# Asignación taxonómica {.unnumbered}

Kraken2 es una herramienta para perfilar la composición taxonómica de comunidades microbianas a partir de datos de metagenoma tipo shotgun. Se basa en la comparación de fragmentos cortos de secuencia (k-mers) contra una base de datos taxonómicamente indexada. Cada k-mer está asociado al nodo taxonómico más específico posible (o a su ancestro común más bajo si es compartido), y la clasificación de cada lectura se realiza mediante un sistema de votos. Este enfoque permite una clasificación rápida y escalable para grandes volúmenes de datos. Dado que el conteo de lecturas no refleja abundancia celular real, Bracken usa la salida de Kraken2 y un modelo probabilístico basado en la distribución esperada de k-mers por genoma para redistribuir lecturas ambiguas y estimar abundancias taxonómicas más precisas.

Para este taller usaremos secuencias obtenidas del artículo *The Alterations of Vaginal Microbiome in HPV16 Infection as Identified by Shotgun Metagenomic Sequencing*.En este estudio se realizó un perfilamiento metagenómico mediante  *Whole Genome Shotgun* (WGS) de microbiota vaginal positiva y negativa para  el virus del papiloma humano (VPH). Por lo tanto, tendremos 3 muestras de microbiota VPH-negativo (N) y 3 muestras para VPH-positivo (INF).

Las muestras fueron secuenciadas con el equipo HiSeq X Ten de Illumina. Son secuencias pareadas con estrategia WGS y son un submuestreo de 200000 lecturas por muestra. Los datos se encuentran en la carpeta `Taller_6` de `datasets`. Copie la carpta completa al directorio de su grupo.


::: {.callout-note appearance="simple"}
## Objetivos
1. Aplicar el análisis metagenómico con Kraken2 a muestras de microbiota y aprender a utilizar datos de secuenciación shotgun para perfilar la composición taxonómica de comunidades microbianas.
2. Comprender los pasos y aprender a visualizar los datos de perfilado taxonómico.
:::

::: {.callout-important appearance="simple"}
Inicie la sesión interactiva asignando 16 GB de memoria. Se recomienda también generar scripts ejecutables para facilitar la reproducibilidad. Además, por favor adjuntar capturas de pantalla de los comandos ejecutados y de las visualizaciones generadas para cada punto.
:::

## I. Limpieza de secuencias

1. Primero es necesario limpiar las lecturas, lo haremos usando primero *FastQC* y *Fastp* como ya lo han usado anteriormente. Recuerden los ambientes que deben activar (en serie) para esos dos programas. Realice el filtrado por calidad considerando exclusivamente los siguientes criterios: (1) Aplicar un umbral mínimo de calidad por base de Phred ≥ 30, (2) Descartar las lecturas en las que más del 10% de las bases presenten baja calidad, y (3) Eliminar las lecturas cuya longitud final sea menor a 50 nucleótidos después del filtrado.

2. En ambos casos adjunte los comandos usados y los pantallazos de los cambios en la calidad de las secuencias antes y después de la limpieza. También indique el porcentaje de secuencias que NO pasaron los filtros de la limpieza.

3. Repita el proceso para cada conjunto de archivos.

## II. Creación de un perfil taxonómico

*Kraken2* acepta como entrada lecturas cortas de un solo experimento de secuenciación metagenómica tipo *shotgun* y genera la lista de microorganismos detectados y sus abundancias relativas; puede procesar tanto lecturas pareadas (*paired-end*) como no pareadas (*single-end*). Active el módulo o el entorno correspondiente en Conda para *Kraken2* y revise la documentación para familiarizarse con su uso y los parámetros disponibles antes de ejecutarlo.

4. Ejecute *Kraken2* sobre cada par de archivos *FASTQ* limpios, teniendo en cuenta que se trata de lecturas pareadas. La base de datos a utilizar se encuentra en: DB="/hpcfs/shared/bcem/databases/kraken2/Standard/20241228"

Pruebe primero con una sola muestra y asegúrese de que el comando se ejecuta correctamente. Luego envíe el procesamiento del resto de las muestras como un job en bash. Para la ejecución de múltiples archivos, consulte el recurso de ayuda proporcionado y modifíquelo para incluir los parámetros especificados anteriormente.

a. ¿Cuál fue el comando que ejecutó? Explíquelo.
b. ¿Qué archivos de salida se generan por muestra? Descríbalos.

## III. Ajuste de abundancias con Bracken

5. Una vez finalizada la clasificación con *Kraken2*, utilice los archivos `.report` generados para estimar abundancias ajustadas con *Bracken*.

Ejecute Bracken sobre cada archivo `.report` individualmente. Un ejemplo de comando es:

```bash
bracken \
    -d /hpcfs/shared/bcem/databases/kraken2/Standard/20241228 \
    -i X \
    -o muestra.bracken \
    -r 150 \
    -l S
```

a. Describa el comando que ejecutó y los archivos de salida que se generan por muestra.
b. Repita el proceso estimando abundancias a nivel de familia pero guarde los resutados en una carpeta diferente.

6. Para combinar los resultados individuales de Bracken en una sola matriz, puede utilizar el script `merged_bracken.py`. Este script toma como entrada los archivos .bracken de cada muestra presentes en la carpeta y genera una tabla combinada. Asegúrese de antes de ejecutar el script en su carpeta solo tenga los archivos `.bracken` que desea combinar.

::: {.callout-important appearance="simple" collapse="true"}
Debe cargar o activar el entorno de Python
:::

```bash
python merged_bracken.py
```

O especificando la ruta completa del entorno:

```bash
~/.conda/envs/bracken_env/bin/python merged_bracken.py
```

Este script genera una tabla combinada donde las filas corresponden a taxones, las columnas corresponden a muestras, y los valores representan abundancias estimadas por Bracken

a. ¿Qué son scripts de pyton y qué los diferencia con los scripts de bash?
b. ¿Por qué el conteo bruto de Kraken2 no representa abundancia celular real?
c. ¿Qué significa que Bracken redistribuya lecturas asignadas a niveles taxonómicos superiores?


## IV. Visualización de resultados

::: {.callout-important appearance="simple"}
Para interpretar mejor los resultados, busque la información relacionada con el proyecto. Revise los códigos de acceso de las muestras, busque en la base de datos de secuenciación a qué tipo de muestra corresponde cada código.
:::

A partir de la tabla de abundancias relativas por muestra, es posible realizar distintos análisis ecológicos (por ejemplo, diversidad alfa y beta) o generar diversas visualizaciones. En este caso, nos enfocaremos únicamente en una visualización muy común en estudios de microbioma: el mapa de calor (heatmap). Este punto deberá realizarse de manera autónoma:

7. Descargue la tabla combinada de abundancias relativas generada previamente (al nivel taxonómico de inetrés, puede ser familia).
Cárguela en R. Elija las familias más abundantes (por ejemplo, top 20). Utilice el paquete de R de su preferencia (por ejemplo, pheatmap o ggplot2) para generar un mapa de calor.

a. Adjunte el gráfico y su interpretación
b. ¿Qué otros tipos de visualizaciones podrían ser útiles para interpretar los resultados de perfilado taxonómico? 
c. Aunque no se va a realizar en este taller, mencione un tipo de tranformación de datos que podría ser útil para mejorar la visualización y análisis de los resultados de perfilado taxonómico, y explique brevemente por qué.


8. Es posible crear otras visualizaciones usando pie charts, puede hacerlo de forma interactiva usando Krona, que genera gráficos jerárquicos en formato HTML. Para esto es necesario convertir los archivos .bracken a un formato compatible con Krona, donde la primera columna representa la abundancia y la segunda columna el taxón correspondiente.

::: {.callout-important appearance="simple" collapse="true"}
Recuerde cargar o activar el entorno de *Krona*.
:::

El siguiente comando extrae esa información del archivo .bracken:

```bash
awk 'NR>1 {print $6 "\t" $1}' sample.bracken > sample_krona.txt
```

Para generar visualización interactiva

```bash
ktImportText sample_krona.txt -o sample.html
```

a. Explique los resultados obtenidos en la visualización de Krona. 
b. ¿Qué opina de este tipo de gráficos?


9. Haga un cuadro comparativo y mencione las ventajas y desventajas entre las herramientas de anotación taxonómica Krake2, Metaphlan y MEGAN.

