---
lang: 'es'
toc: true
code-annotations: select
---
# Ensamblaje de metagenomas {.unnumbered}

El ensamblaje metagenómico consiste en reconstruir secuencias más largas (contigs) a partir de millones de lecturas obtenidas por secuenciación shotgun de una comunidad microbiana. A diferencia del ensamblaje de un genoma aislado, en metagenómica trabajamos con ADN proveniente de múltiples organismos, lo que aumenta considerablemente la complejidad computacional y biológica del proceso.

El primer objetivo del ensamblaje es construir contigs, es decir, secuencias continuas generadas a partir del solapamiento o conexión de lecturas. Estos contigs representan fragmentos reconstruidos de los genomas presentes en la comunidad. Posteriormente, estos contigs pueden agruparse mediante binning, proceso que busca reconstruir genomas individuales (MAGs) a partir de la información de cobertura, composición y co-abundancia. El binning constituye la etapa final en la reconstrucción de genomas a partir de datos metagenómicos.

En este taller nos enfocaremos en la primera parte del proceso: el ensamblaje hasta la generación de contigs. Aun sin realizar binning, los contigs permiten realizar análisis importantes, como anotación funcional, perfil metabólico, identificación de genes de interés y comparación entre comunidades. De esta manera, los contigs ya representan una unidad biológicamente informativa, incluso antes de la reconstrucción completa de genomas.


::: {.callout-note appearance="simple"}
## Objetivos
Desarrollar competencias prácticas para el ensamblaje de datos metagenómicos hasta la obtención de contigs y su posterior anotación funcional mediante herramientas bioinformáticas.
1. Comprender los principios básicos del ensamblaje de secuencias metagenómicas y su evaluación de calidad.
2. Realizar el ensamblaje de lecturas metagenómicas hasta la obtención de contigs.
3. Aplicar herramientas bioinformáticas para la anotación funcional de los contigs obtenidos.
4. Interpretar los resultados de la anotación funcional en un contexto biológico.
:::

Para este taller se usarán [muestras de metagenomas](https://www.ncbi.nlm.nih.gov/sra/SRX9865427) de pacientes con [VIH y sin VIH](https://www.frontiersin.org/journals/microbiology/articles/10.3389/fmicb.2021.667718/full). Los datos de secuenciación están disponibles en el directorio `~/datasets/Taller_6`. Los archivos son:

| Archivo                 | Descripción                                |
|-------------------------|--------------------------------------------|
| SRR13452514_1.f10.fastq.gz  | Muestra forward control al 10% (Q_C3)          |
| SRR13452514_2.f10.fastq.gz  | Muestra reverse control al 10% (Q_C3)           |
| SRR13452521_1.f10.fastq.gz  | Muestra forward caso al 10% (Q_H1)              |
| SRR13452521_2.f10.fastq.gz  | Muestra forward caso al 10% (Q_H1)              |

Note que estos fueron submuestreados al 10% para facilitar el análisis usando [rasusa](https://github.com/mbhall88/rasusa):

```bash
rasusa -i <samplereads>.fastq.gz -f 0.1 -o <samplereads>.f10.fastq.gz
```

## I. Ensamble y análisis de calidad de MAGs (50/100)

1. Realice el ensamble de las muestras metagenómicas (control y caso) con los parámetros por defecto para librerías pareadas usando el software [megahit](https://github.com/voutcn/megahit). 

a. ¿Cuáles son los parámetros por defecto del programa? Justifique su respuesta.
b. ¿Que parámetros considera que sería útil modificar? Justifique su respuesta.

:::{.callout-important}
Recuerde activar el ambiente adecuado: `conda activate megahit`
:::

```bash
megahit -1 <forwardreads>.f10.fastq.gz -2 <reversereads>.f10.fastq.gz -o control
```

::: {.callout-caution}
## Bono
Realice el ensamble con los parámetros por defecto y con los parámetros que usted considera útiles modificar. Compare los resultados y justifique su elección. Luego realice el ensamble usando otro ensamblador como [SPAdes](https://github.com/ablab/spades) en modo metagenómico. Compare los resultados obtenidos con los de `megahit`. ¿Cuál ensamblador considera que es mejor para este tipo de datos? Justifique su respuesta[^1].
:::

2. Utilice [QUAST](https://github.com/ablab/quast) v5.0.2 para revisar los estadísticos del ensamblaje. Genere y muestre el reporte. 

a. ¿Qué le indican la longitud total, el número de *contigs* totales, el número de *contigs*, y las métricas de N50 y L50? 
b. Revise la siguiente [discusión](http://lh3.github.io/2020/04/08/a-new-metric-on-assembly-contiguity) y explique. 

::: {.callout-tip collapse="true"}
Una manera rápida de calcular las estadísticas sin el reporte visual es usando [seqfu]():

```bash
seqfu stats -n SRR13452514_1.f10.fastq.gz
```

| File              | #Seq      | Total bp    | Avg      | N50   | N75   | N90   | auN    | Min   | Max   |
|-------------------|-----------|-------------|----------|-------|-------|-------|--------|-------|-------|
| SRR13452514_1.f10.fastq.gz     | 4154060   | 627263060   | 151.00   | 151   | 151   | 151   | 0.00   | 151   | 151   |

:::

3. Con base en sus resultados, responda:

a. ¿Qué tan bien cree que se realizó el ensamblaje? 
b. De las dos muestras metagonómicas, cuál cree que tiene mejor calidad? Justifique su respuesta.


## II. Predicción de genes y análisis funcional (50/100)

La predicción de genes es la identificación algorítmica de segmentos de secuencias que son biológicamente funcionales, como los genes codificantes de proteínas, genes codificadores de ARN (e.g, 16S rARN) y secuencias reguladoras. Una vez ensamblado el genoma o el metagenoma, vamos a llevar a cabo la predicción de genes mediante el software [Bakta](https://github.com/oschwengers/bakta). 

4. Ejecute `bakta` sobre cada ensamble realizado (control y caso). Para esto utilice:

:::{.callout-important}
Recuerde activar el ambiente adecuado: `conda activate bakta-1.9.3`
:::

```bash
bakta --threads 8\
 --prefix <prefix>\
 --db ~/.dbs/bakta-db/db-full\
 --output <outdir>\
 --meta\
 --skip-trna\          #<1> 
 --skip-tmrna\         #<2> 
 --skip-rrna \         #<3> 
 --skip-ncrna\         #<4> 
 --skip-ncrna-region\  #<5> 
 --skip-crispr\        #<6> 
 <contigs>.fasta
```
1. Skip tRNA detection & annotation
2. Skip tmRNA detection & annotation
3. Skip rRNA detection & annotation
4. Skip ncRNA detection & annotation
5. Skip ncRNA region detection & annotation
6. Skip CRISPR array detection & annotation

***

5. ¿Qué tipos de archivos de salida genera Bakta? Explique brevemente el contenido y propósito de cada uno. Posteriormente, inspeccione el archivo `FAA`(proteínas predichas) y cuente el número total de regiones codificantes detectadas para cada muestra metagenómica.

6. Ahora realice la clasificación funcional de los genes predichos y visualice los resultados. Para esto, utilice [COGclassifier](https://github.com/moshi4/COGclassifier/). Este software permite realizar la búsqueda de secuencias de consulta en la base de datos COG, pasando por la anotación y clasificación de las funciones de los genes, hasta la generación de figuras. ¿Qué porcentaje de secuencias fueron clasificadas? ¿Qué le indican las gráficas generadas? Adjunta las figuras y describelas.

4. Responda a partir de los conteos de genes predichos y su anotación funcional 

a. ¿Qué diferencias observa entre las dos muestras metagenómicas? 
b. Especule sobre las posibles diferencias en la funcionalidad de la comunidad microbiana en cada una de las muestras (control y caso). Complemente su respuesta mediante la revisión del articulo de referencia[^2].

[^1]: El bono es valido al realizar ambas comparaciones.

[^2]: Bai, X., Narayanan, A., Nowak, P., Ray, S., Neogi, U., & Sönnerborg, A. (2021). Whole-genome metagenomic analysis of the gut microbiome in HIV-1-infected individuals on antiretroviral therapy. Frontiers in Microbiology, 12, 667718.