---
lang: 'es'
toc: true
code-annotations: select
from: markdown+emoji
---

## Binning de metagenomas {.unnumbered}

El *binning* de metagenomas es el proceso mediante el cual se agrupan los *contigs* obtenidos del ensamblaje metagenómico en unidades biológicas más completas, conocidas como *bins* o MAGs (Metagenome-Assembled Genomes). Este proceso es crucial para la reconstrucción de genomas individuales a partir de datos metagenómicos, lo que permite realizar análisis taxonómicos, funcionales y comparativos a nivel de genoma completo. El *binning* se basa en la información de cobertura, composición y co-abundancia de los *contigs* para agruparlos en *bins* que representen genomas individuales o fragmentos genómicos de organismos presentes en la comunidad microbiana.


::: {.callout-note appearance="simple"}
## Objetivos
Comprender las estrategias de binning en metagenómica y generar bins (MAGs), para posteriormente anotarlos, clasificarlos y visualizarlos utilizando herramientas especializadas de análisis genómico.
:::


En este taller se usaran nuevamente las [muestras de metagenomas](https://www.ncbi.nlm.nih.gov/sra/SRX9865427) de pacientes con [VIH y sin VIH](https://www.frontiersin.org/journals/microbiology/articles/10.3389/fmicb.2021.667718/full), que fueron ensambladas a nivel de *contigs* mediante `megahit`. Los *contigs* se encuentran disponibles en el directorio `~/Datasets/Taller8`. Los archivos son:

| Archivo                 | Descripción                                |
|-------------------------|--------------------------------------------|
| control.contigs.renamed.fa  | Contigs de un muestreo al 10% del control (Q_C3)  |
| case.contigs.renamed.fa  |  Contigs de un muestreo al 10% del caso  (Q_H1) |

Note que estos fueron generados usando `megahit`:

```bash
megahit -1 SRR13452514_1.f10.fastq.gz -2 SRR13452514_2.f10.fastq.gz -o <outdir>
megahit -1 SRR13452521_1.f10.fastq.gz -2 SRR13452521_2.f10.fastq.gz -o <outdir>
```

:::{.callout-warning}
Si desean pueden usar los archivos de los *contigs* generados en la práctica anterior por ustedes mismos, bajo su responsabilidad y riesgo :grimacing:
:::

:::{.callout-important}

Tome pantallazo de cada punto del taller y agréguelos en el informe
:::


## I. Binning de MAGs

1. Realice el *binning* de los metagenomas de las dos muestras usando [Vamb](https://github.com/RasmussenLab/vamb?tab=readme-ov-file#how-to-run-using-your-own-input-files). El proceso consta de varias etapas:

    a. Concatenar el catálogo de *contigs* de las muestras de control y caso. 
    b. Mapear las lecturas de cada muestra al catálogo de *contigs* con `minimap2` 
    c. Generar los archivos `BAM` correspondientes. 
    d. Realizar propiamente el *binning* con `vamb`

:::{.callout-important collapse="true"}

Use el ambiente de conda `vamb-4.1.3` para correr `vamb`. Si está enviando un trabajo a un cluster, recuerde que debe activar el ambiente de conda antes de correr el comando, para eso utilice `source activate vamb-4.1.3`. Las funciones `concatenate.py` y el paquete `minimap2` están disponibles en el mismo ambiente.
:::

a. Concatenar el catálogo de genes de las muestras de control y caso. 

```bash
concatenate.py catalogue.fna.gz <contigs-case>.fa <contigs-control>.fa
```

```bash
minimap2 -d catalogue.mmi catalogue.fna.gz;
```

    b y c. Mapear las lecturas de cada muestra al catálogo de *contigs* con `minimap2` y genere los archivos `BAM` correspondientes.

```bash
minimap2 -t 8\
         -N 5\
         -ax sr catalogue.mmi\
         --split-prefix mmsplit\
         <reads-fraction-forward>.fastq.gz <reads-fraction-forward>.fastq.gz\
         | samtools view -F 3584 -b --threads 8 > <{case|control}>.bam
```

::: {.callout-caution}
## Bono
¿Qué hace la linea de comando `samtools view -F 3584 -b --threads 8 > <{case|control}>.bam`
:::

    d. Correr binning con Vamb

```bash
vamb --outdir <outdir> --fasta catalogue.fna.gz --bamfiles <maped-reads-{case|control}>.bam --minfasta 500000 -o C
```

Explique la función del parámetro `--minfasta` en `vamb` y qué valor elegiría en este contexto. Justifique su elección. Además, indique si existe otra forma de obtener los archivos *fasta* de los bins generados por `vamb` sin utilizar el parámetro `--minfasta`, y explique brevemente cómo se podría hacer.


2. Revise los *bins* generados utilizando *CheckM*. Muestre y describa las estadísticas de calidad de los *bins* obtenidos y concluya sobre su calidad.

3. Discuta el número de *bins* generados en relación con cada una de las muestras. ¿Qué puede concluir sobre el número y las características de los *bins* obtenidos en cada muestra?

## II. Clasificación, Anotación y Visualización de los *bins*

1. Para clasificar los *bins* generados, use la herramienta [GTDB-Tk](https://github.com/Ecogenomics/GTDBTk) y el comando `classify_wf`. Revise la clasificación taxonómica de los *bins* y describa el lineaje taxonómico de los *bins* de cada muestra.

:::{.callout-important collapse="true"}
Para la clasificación de los *bins* generados, use el ambiente de conda `gtdbtk-2.3.2`. Si está enviando un trabajo a un cluster, recuerde que debe activar el ambiente de conda antes de correr el comando, para eso utilice `conda activate gtdbtk-2.3.2`.

```bash
gtdbtk classify_wf --genome_dir <bins-dir> --out_dir <classified-bins> --skip_ani_screen
```
:::

2. Anote el *bin* más completo de cada muestra de forma general mediante `bakta` del mismo modo que anotó los *contigs* en la práctica anterior. Muestre el resumen de la anotación del *bin* más completo en cada una de las muestras.

3. Como se ha discutido a lo largo del curso, existen múltiples herramientas y enfoques para el análisis de datos genómicos y metagenómicos. Proksee es una plataforma que permite visualizar genomas procarióticos y explorar de manera interactiva sus anotaciones, facilitando la interpretación de la organización genómica y de las características funcionales de los bins o MAGs obtenidos. Ingrese a Proksee y describa las principales características de esta herramienta, así como su posible utilidad para analizar y visualizar los bins generados en esta práctica.

::: {.callout-caution}
## Bono
Ingrese a [Proksee](https://proksee.ca) y visualice el *bin* más completo de cada muestra. Describa las características y muestre la visualización que obtiene luego de utilizar los parámetros de la interfaz.^[Notarás que la anotación de los genomas o *bins* puede hacerse directamente en Proksee, esto es posible pero recuerde dar la información de las estadísticas de anotación.]
:::

